// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf_unity_custom_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from protobuf_unity_custom_options.proto</summary>
public static partial class ProtobufUnityCustomOptionsReflection {

  #region Descriptor
  /// <summary>File descriptor for protobuf_unity_custom_options.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtobufUnityCustomOptionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiNwcm90b2J1Zl91bml0eV9jdXN0b21fb3B0aW9ucy5wcm90bxogZ29vZ2xl",
          "L3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG86MAoHcHJpdmF0ZRIdLmdvb2ds",
          "ZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYzbEDIAEoCDo6Cg9wcml2YXRlX21l",
          "c3NhZ2USHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYzrEDIAEo",
          "CGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
        new pbr::GeneratedClrTypeInfo(null, null));
  }
  #endregion

}

#endregion Designer generated code
